package com.fanjie.travel.mapper;

import com.fanjie.travel.model.dto.UserDTO;
import com.fanjie.travel.model.po.TravelUser;
import java.util.List;

import com.fanjie.travel.model.vo.UserVO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TravelUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_user
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_user
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    int insert(UserVO vo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_user
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    List<UserDTO> selectByPhone(UserVO vo);

    List<UserDTO> selectByPhoneAndPass(UserVO vo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_user
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    List<UserDTO> selectAll();

    List<UserDTO> selectAllBySelect(String str);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_user
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    int updateByPrimaryKey(UserVO vo);
}
