package com.fanjie.travel.model.po;

public class TravelUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.id
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.phone
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.password
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.gender
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.age
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.mail
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.profile
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private String profile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_user.head
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    private String head;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.id
     *
     * @return the value of travel_user.id
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.id
     *
     * @param id the value for travel_user.id
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.phone
     *
     * @return the value of travel_user.phone
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.phone
     *
     * @param phone the value for travel_user.phone
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.password
     *
     * @return the value of travel_user.password
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.password
     *
     * @param password the value for travel_user.password
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.gender
     *
     * @return the value of travel_user.gender
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.gender
     *
     * @param gender the value for travel_user.gender
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.age
     *
     * @return the value of travel_user.age
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.age
     *
     * @param age the value for travel_user.age
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.mail
     *
     * @return the value of travel_user.mail
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.mail
     *
     * @param mail the value for travel_user.mail
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.profile
     *
     * @return the value of travel_user.profile
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.profile
     *
     * @param profile the value for travel_user.profile
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_user.head
     *
     * @return the value of travel_user.head
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_user.head
     *
     * @param head the value for travel_user.head
     *
     * @mbg.generated Sat Feb 06 16:08:13 CST 2021
     */
    public void setHead(String head) {
        this.head = head;
    }
}